### ISSUE TITLE
dataloader

### ISSUE THREAD

**Issue by jiouai** [gd2016229035/faster-rcnn-rgbd#2]
Hello, 
I have some problem about dataloader.
Could someone gave me some help?

$ python3 train.py train --env='fasterrcnn' --plot-every=20
======user config========
{'caffe_pretrain': False,
 'caffe_pretrain_path': './vgg16_caffe.pth',
 'concat_layer': 1,
 'data': 'voc',
 'debug_file': '/tmp/debugf',
 'env': 'fasterrcnn',
 'epoch': 13,
 'load_depth_extimater': '../depth_etimation/model_best.pth_L2_U-net_vgg11.tar',
 'load_depth_path': None,
 'load_head': None,
 'load_path': None,
 'load_rgb_path': None,
 'load_rpn': None,
 'lr': 0.001,
 'lr_decay': 0.1,
 'max_size': 1000,
 'min_size': 600,
 'num_workers': 4,
 'plot_every': 20,
 'port': 8097,
 'pretrained_model': 'vgg16',
 'roi_sigma': 1.0,
 'rpn_sigma': 3.0,
 'test_num': 10000,
 'test_num_workers': 4,
 'use_adam': False,
 'use_chainer': False,
 'use_drop': False,
 'voc_data_dir': '/home/jiou/faster-rcnn-rgbd/faster-rcnn-rgbd/NYUv2/',
 'weight_decay': 0.0005}
==========end============
load data
model construct completed
Traceback (most recent call last):
  File "train.py", line 150, in <module>
    fire.Fire()
  File "/home/jiou/.local/lib/python3.5/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/jiou/.local/lib/python3.5/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/jiou/.local/lib/python3.5/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 84, in train
    for ii, (img, img_depth, bbox_, label_, scale) in tqdm(enumerate(dataloader)):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 953, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/jiou/faster-rcnn-rgbd/faster-rcnn-rgbd/data/dataset.py", line 160, in __getitem__
    ori_img, ori_img_depth, bbox, label, difficult = self.db.get_example(idx)
  File "/home/jiou/faster-rcnn-rgbd/faster-rcnn-rgbd/data/voc_dataset.py", line 145, in get_example
    label = np.stack(label).astype(np.int32)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/shape_base.py", line 349, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

**Comment by gd2016229035** [comment]
@jiouai Sorry for my late reply...because I have not check this code for a long time.
It looks like there are empty labels in your dataset, because the original faster-rcnn implementation(from https://github.com/chenyuntc/simple-faster-rcnn-pytorch ,PyTorch0.3 version) requires that every xml file should have its bbox label. NYU object detection dataset Maybe has empty label , so you can simply delete them~
